Review
naitov/epam-selenium-practice pull request #6
Opened 2022-12-20 21:02 UTC by naitov

2022-12-20 22:41 UTC, tsbwn requested changes
Take a look at comments resolve if clear. Let discuss the changes later

2022-12-20 22:41 UTC, tsbwn commented on src/test/java/hurt_me_plenty/page/GooglePricingCalculatorEstimatePage.java
> +            Matcher matcher = Pattern.compile("\\n").matcher(row);
You could simplify it by using String.split() and list.addAll().
May be play with java stream api here but it's fine

2022-12-20 22:41 UTC, tsbwn commented on src/test/java/hurt_me_plenty/page/GooglePricingCalculatorEstimatePage.java
> +        String elementText = createNewPresenceElement(3, "//*[@id='compute']/descendant::b[contains(text(), 'Estimated Component Cost')]")
You sure there is no simpler locator w/o descendant etc? 
Also, the xpathes look better if present in file as a static variables. But this is also acceptable since used ones

2022-12-20 22:41 UTC, tsbwn commented on src/test/java/hurt_me_plenty/page/GooglePricingCalculatorFormPage.java
> +        numberOfInstancesInputField.sendKeys("4");
test data in the page

2022-12-20 22:41 UTC, tsbwn commented on src/test/java/hurt_me_plenty/page/GoogleCloudHomePage.java
> +            return new GooglePricingCalculatorFormPage(driver, searchResultLink.getAttribute("href"));
This is weird. Why do you return URL and then open it in other page class instead of just clicking the result link? This getting link and passing to the other page file seems unnecessary. 
Furthermore you miss check here that actual click transfer user to the necessary page. Page opened by direct link != opening page by click

2022-12-20 22:41 UTC, tsbwn commented on src/test/java/hurt_me_plenty/page/GooglePricingCalculatorFormPage.java
> +    @FindBy(xpath = "//*[text()='Committed usage']/parent::*")
usage 'parent' over the locators seems unnecessary because it complicates the code. Is there are better ways?

2022-12-20 22:41 UTC, tsbwn commented on src/test/java/hurt_me_plenty/page/GooglePricingCalculatorFormPage.java
> +        driver.switchTo().frame(iFrameElement);
- why switching to 0 if after switching to iFrameElement?
- When do we switch back to default context?

2022-12-20 22:41 UTC, tsbwn commented on src/test/java/hurt_me_plenty/page/GooglePricingCalculatorFormPage.java
> +    @FindBy(xpath = "//div[@class='md-text' and contains(text(), 'Free')]/parent::md-option")
test data in locator

2022-12-20 22:41 UTC, tsbwn commented on src/test/java/hurt_me_plenty/page/GooglePricingCalculatorFormPage.java
> +    @FindBy(xpath = "//div[@class='md-text'][contains(text(), 'Regular')]/parent::md-option")
test data in locator here and down below by file

2022-12-20 22:41 UTC, tsbwn commented on src/test/java/hurt_me_plenty/test/GooglePricingCalculatorTest.java
> +        GooglePricingCalculatorEstimatePage estimatePage = calculatorFormPage.fillAllNecessaryFields().addToEstimate();
>fillAllNecessaryFields

what do we fill? Impossible to understand from the test

2022-12-20 22:41 UTC, tsbwn commented on src/test/java/hurt_me_plenty/test/GooglePricingCalculatorTest.java
> +    public void ActualAndExpectedSumsShouldBeEqual() throws NoSuchResultException, ParseException {
code style

2022-12-20 22:41 UTC, tsbwn commented on src/test/java/hurt_me_plenty/test/GooglePricingCalculatorTest.java
> +    @Test(description = "Actual and expected sums should be equal")
Test description is too basic. Need to reformulate to be more specific and distinguishable

2022-12-20 22:41 UTC, tsbwn commented on src/test/java/hurt_me_plenty/test/GooglePricingCalculatorTest.java
> +    public void ResultingFieldsShouldContainExpectedParameters() throws NoSuchResultException {
code style

2022-12-20 22:41 UTC, tsbwn commented on src/test/java/hurt_me_plenty/page/GoogleCloudHomePage.java
> +    private static final String SEARCH_TERM = "Google Cloud Pricing Calculator";
test data in page

2022-12-20 22:41 UTC, tsbwn commented on src/test/java/hurt_me_plenty/page/GooglePricingCalculatorFormPage.java
> +    WebElement iFrameElement;
private?

2022-12-20 22:58 UTC, naitov commented on src/test/java/hurt_me_plenty/page/AbstractPage.java
> +    WebElement createNewPresenceElement(int durationSec, String xpath) {
newPresenseElementWithWait looks ok?

2022-12-20 23:00 UTC, naitov commented on src/test/java/hurt_me_plenty/page/GoogleCloudHomePage.java
> +        searchField.sendKeys(SEARCH_TERM);
does it mean that ALL incoming parameters must be in test class and have privatestatic final modifiers?

2022-12-20 23:04 UTC, naitov commented on src/test/java/hurt_me_plenty/exceptions/NoSuchResultException.java
> +public class NoSuchResultException extends Exception {
Idea was to throw smth unique when method can't find matched result. ofk it was unnecessary, just for better readability

2022-12-20 23:06 UTC, naitov commented on src/test/java/hurt_me_plenty/page/GoogleCloudHomePage.java
> +            throw new NoSuchResultException("Search term is missing in search results");
do you mean just deletetion of this part?

```
else {
            throw new NoSuchResultException("Search term is missing in search results");
```

2022-12-20 23:21 UTC, naitov commented on src/test/java/hurt_me_plenty/page/GooglePricingCalculatorEstimatePage.java
> +            Matcher matcher = Pattern.compile("\\n").matcher(row);
I tried do so, but inside the for loop I need to increase array index, to add new list elements, but I can't know how many delimiters has any one of list elements, thus I had to track regex entry occurrences anyway :)

2022-12-20 23:24 UTC, naitov commented on src/test/java/hurt_me_plenty/page/GooglePricingCalculatorEstimatePage.java
> +        String elementText = createNewPresenceElement(3, "//*[@id='compute']/descendant::b[contains(text(), 'Estimated Component Cost')]")
do you mean just as string fields? Also why they must be static?

2022-12-21 10:24 UTC, tsbwn requested changes

2022-12-21 10:24 UTC, tsbwn commented on src/test/java/hurt_me_plenty/page/AbstractPage.java
> +    WebElement createNewPresenceElement(int durationSec, String xpath) {
Better. But you do not create anything, you are getting. And need to distinguish different kinds of waits here.
E.g.
`getElementWithPresenceWait` + `getClickableElement `or `getElementWithClickableWait`

2022-12-21 10:24 UTC, tsbwn commented on src/test/java/hurt_me_plenty/page/GoogleCloudHomePage.java
> +        searchField.sendKeys(SEARCH_TERM);
Yes, that's better practice to have your test data right inside test. If you have too much test data or it's a massive text files, like big json or something -- you might want to have it in a separate files and load up them when necessary in test.

This will help greatly for maintainability of your tests by other project members.

Hard coding test data in pages or locators is a bad practice. You obviously can do it for certain things that do not relate much to test object. But search request, SKU parameters like 'FREE' plan is a test data

2022-12-21 10:24 UTC, tsbwn commented on src/test/java/hurt_me_plenty/page/GoogleCloudHomePage.java
> +            throw new NoSuchResultException("Search term is missing in search results");
I mean you can replace your if by assertion here.
```
assertThat("Search term should have results", SearchResultText.getText(), is(SEARCH_TERM));
return whatever_you_need;
```
if assert fails, it will end the test with error

2022-12-21 10:24 UTC, tsbwn commented on src/test/java/hurt_me_plenty/page/GooglePricingCalculatorEstimatePage.java
> +            Matcher matcher = Pattern.compile("\\n").matcher(row);
Not sure if I got it right, let's discuss in private

2022-12-21 10:24 UTC, tsbwn commented on src/test/java/hurt_me_plenty/page/GooglePricingCalculatorEstimatePage.java
> +        String elementText = createNewPresenceElement(3, "//*[@id='compute']/descendant::b[contains(text(), 'Estimated Component Cost')]")
`private static final String SUM_FIELD_XPATH = "//*[@id='compute']/descendant::b[contains(text(), 'Estimated Component Cost')]";`

static because you do not change for different objects. It's actually like a constant, you do not change this value during execution at all

2022-12-23 18:20 UTC, merged